# Generated by Django 3.2.8 on 2021-10-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avpms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, default='pro_pic.png', null=True, upload_to='driver_image/'),
        ),
    ]
