# Generated by Django 3.2.8 on 2021-10-29 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avpms', '0002_alter_driver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avpms.driver'),
        ),
    ]
