# Generated by Django 3.2.8 on 2021-10-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avpms', '0003_alter_daily_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_report',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
