# Generated by Django 3.2.8 on 2021-10-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avpms', '0004_alter_daily_report_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_report',
            old_name='user',
            new_name='driver',
        ),
        migrations.AlterField(
            model_name='daily_report',
            name='qm_permission',
            field=models.BooleanField(default=False),
        ),
    ]
