# Generated by Django 3.2.8 on 2021-10-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avpms', '0005_auto_20211029_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='nco',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='nco',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
